#Conda enviroment file format -
#https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

#conda environment specification 
# this dependencies will be automaically provisioned for runs with user management dependencies = false


name: Myenv

dependencies:
#The oython interpreter version, current Azure ML only supports 3.5.2 and later
  - python=3.7
  -pip:
   -azure
   -azure-ml-api-sdk
   -inference-schema
   -azureml-defaults
  -numoy>=1.16.0,<=1,16.2
  -pandas
  -scikit-learn=0.22.0
  -joblib

channels:
  - conda-forge
